# Generated by Django 4.2 on 2023-04-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_profile_image_alter_profile_info_alter_profile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='media/profile', verbose_name='الصورة الشخصيه'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.IntegerField(null=True, verbose_name='السعر'),
        ),
    ]
